export default class CommonConstants {
  /*
   * Hundred percent
   * */
  static readonly FULL_PERCENT: string = '100%';
  /*
   * column space */
  static readonly COLUMN_SPACE: number = 12;
  /*
   * Text font weight
   * */
  static readonly TEXT_FONT_WEIGHT: number = 700;
  /*
   * font weight 500
   * */
  static readonly FONT_WEIGHT_500: number = 500;
  /*
   * font weight 400
   * */
  static readonly FONT_WEIGHT_400: number = 400;
  /*
   * font family
   * */
  static readonly FONT_FAMILY_BLACK: string = '鸿蒙黑体';
  /*
   * NavDestination title
   * */
  static readonly NAV_DESTINATION_TITLE: string = '详情';
  /*
   * NavDestination encryption title
   * */
  static readonly NAV_ENCRYPTION_TITLE: string = '加解密';
  /*
   * NavDestination signature title
   * */
  static readonly NAV_SIGNATURE_TITLE: string = '签名验签';
  /*
   * NavDestination message summary title
   * */
  static readonly NAV_MESSAGE_SUMMARY_TITLE: string = '消息摘要';
  /*
   * NavDestination message auth code title
   * */
  static readonly NAV_MESSAGE_AUTH_CODE_TITLE: string = '消息验证码';
}