import { cryptoFramework } from '@kit.CryptoArchitectureKit';
import { buffer } from '@kit.ArkTS';
import CommonConstants from '../constants/CommonConstants';
import { SummaryItem } from '../viewmodel/SummaryItem';
import { getResourceString } from '../utils/ResourceString';

@Builder
export function SummaryDetailBuilder() {
  SummaryDetail();
}

@Component
export struct SummaryDetail {
  @Consume('pageInfos') pageInfos: NavPathStack;
  @State SummaryItem: SummaryItem = new SummaryItem($r('app.string.empty'), '');
  @State message: string = '';
  @State MessageResult: string = '';

  aboutToAppear(): void {
    this.SummaryItem = this.pageInfos.getParamByName('SummaryDetail')[0] as SummaryItem;
  }

  async doSummary(message: string, type: string) {
    if (type === 'SHA256Segments') {
      let mdAlgName = "SHA256"; // Digest algorithm name.
      let md = cryptoFramework.createMd(mdAlgName);
      let messageData = new Uint8Array(buffer.from(message, 'utf-8').buffer);
      // Assume that the segment update is performed in the unit of 20 bytes. in practice,there is no requirement.
      let updateLength = 20;
      for (let i = 0; i < messageData.length; i += updateLength) {
        let updateMessage = messageData.subarray(i, i + updateLength);
        let updateMessageBlob: cryptoFramework.DataBlob = { data: updateMessage };
        await md.update(updateMessageBlob);
      }
      let mdOutput = await md.digest();
      this.MessageResult = `${mdOutput.data}`;
    } else {
      let mdAlgName = type; // Digest algorithm name.
      let md = cryptoFramework.createMd(mdAlgName);
      await md.update({ data: new Uint8Array(buffer.from(message, 'utf-8').buffer) });
      let mdResult = await md.digest();
      this.MessageResult = `${mdResult.data}`;
    }
  }

  build() {
    NavDestination() {
      Column() {
        Column() {
          TextInput({ text: this.message, placeholder: $r('app.string.text_summary') })
            .margin({ top: $r('app.float.margin_top_sixteen') })
            .backgroundColor(Color.White)
            .onChange((value) => {
              this.message = value;
            })

          Column() {
            Text($r('app.string.summary_result'))
              .margin({ left: $r('app.float.margin_left_five') })

            TextArea({ text: this.MessageResult })
              .height($r('app.float.textarea_height'))
              .margin({ top: $r('app.float.margin_top_sixteen') })
              .backgroundColor(Color.White)
              .enabled(false)
          }
          .alignItems(HorizontalAlign.Start)
          .margin({ top: $r('app.float.margin_top_sixteen') })
        }

        Button() {
          Text(this.SummaryItem.name)
            .fontSize($r('app.float.common_font'))
            .fontColor(Color.White)
        }
        .onClick(() => {
          this.doSummary(this.message, this.SummaryItem.type);
        })
        .enabled(this.message ? true : false)
        .width(CommonConstants.FULL_PERCENT)
        .height($r('app.float.button_height'))
        .margin({ top: $r('app.float.margin_top_sixteen') })
      }
      .padding({
        left: $r('app.float.medium_padding'),
        right: $r('app.float.medium_padding'),
        bottom: $r('app.float.medium_padding')
      })
      .height(CommonConstants.FULL_PERCENT)
      .justifyContent(FlexAlign.SpaceBetween)
    }
    .title(getResourceString(this.SummaryItem.name, this))
    .backgroundColor($r('app.color.background_page'))
  }
}